
TRANSLATIONS = {
    "ja": {
        "app_title": "鳴潮 音骸スコア計算機",
        "char_setting_title": "キャラクター設定",
        "char_name": "キャラクター名:",
        "char_name_en": "英語名:",
        "char_name_en_placeholder": "英語名を入力 (例: Calcharo)",
        "cost_config": "コスト構成:",
        "echo_5_slot_config": "エコー5枠構成",
        "cost_echo": "コスト{}エコー",
        "effective_substats_weights": "有効サブステータスと重み係数入力欄（5個）",
        "effective_substat_n": "有効サブステータス{}",
        "weight": "重み:",
        "save": "保存",
        "close": "閉じる",
        "error": "エラー",
        "enter_char_name": "キャラクター名を入力してください",
        "enter_char_name_en": "英語名を入力してください",
        "echo_main_stat_unselected": "エコー{}メインステータス未選択",
        "save_complete": "保存完了",
        "save_msg": "{}の設定を保存しました",
        "basic_settings": "基本設定",
        "character": "キャラ:",
        "input_mode": "入力:",
        "manual": "手動",
        "ocr": "OCR",
        "auto_main": "メイン自動",
        "calc_mode": "計算:",
        "batch": "一括",
        "single_only": "選択のみ",
        "calculate": "計算",
        "export_txt": "TXT出力",
        "clear_all": "全クリア",
        "clear_tab": "タブクリア",
        "char_setting": "キャラ設定",
        "help": "ヘルプ",
        "ocr_image": "OCR画像",
        "load_image": "画像読込",
        "paste_clipboard": "クリップボードから貼付 (Ctrl+V)",
        "perform_crop": "切り取り実行",
        "crop_mode": "切り取りモード:",
        "drag": "ドラッグ",
        "percent": "％指定",
        "top_percent": "上%:",
        "right_percent": "右%:",
        "no_image": "No Image",
        "calc_result": "計算結果",
        "log": "ログ",
        "main_stat": "メイン",
        "substats": "サブステータス",
        "ratio": "倍率: {}",
        "tab_clear_success": "タブ '{}' をクリアしました",
        "export_success": "エクスポート成功",
        "export_msg": "結果をTXTファイルにエクスポートしました。",
        "ocr_library_missing": "OCRモードには以下のライブラリが必要です:\n{}\n\n手動モードに戻します。",
        "ocr_auto_fill_fail_no_tab": "OCR自動入力失敗: タブが選択されていません",
        "ocr_auto_fill_fail_tab_not_found": "OCR自動入力失敗: タブ'{}'が見つかりません",
        "ocr_auto_fill_success": "OCR自動入力: サブ{} → {} {}{}",
        "clipboard_no_image": "クリップボードに画像がありません",
        "clipboard_error": "クリップボード読み込みエラー: {}",
        "image_not_loaded": "画像が読み込まれていません",
        "file_not_found": "ファイルが見つかりません:\n{}",
        "image_select_cancelled": "画像選択をキャンセルしました",
        "select_image_file": "画像ファイルを選択",
        "image_files": "画像ファイル",
        "all_files": "すべてのファイル",
        "pillow_required": "OCRモードを利用するにはPillowが必要です。",
        "crop_cancel": "クロップキャンセル",
        "image_loaded": "画像を読み込みました: {}",
        "ocr_success": "OCR成功 (文字数: {})",
        "ocr_no_text": "OCR結果: テキスト未検出",
        "ocr_tesseract_not_found": "Tesseract実行ファイルが見つかりません (設定: {})",
        "ocr_lang_data_error": "OCR言語データ(jpn)が見つかりません。\nTesseractの日本語辞書(jpn.traineddata)をインストールしてください。\n詳細: {}",
        "ocr_process_error": "OCR処理でエラーが発生しました:\n{}",
        "data_save_success": "データを保存しました",
        "data_load_success": "データ読込完了（必要な項目を反映）",
        "data_load_error": "読込失敗: {}",
        "settings_loaded": "設定を読み込みました",
        "language": "言語 (Language):",
        "restart_required": "再起動が必要です",
        "restart_msg": "言語設定を変更しました。適用するにはアプリケーションを再起動してください。",
        "language_changed_title": "言語変更",
        "language_changed_message": "言語設定を変更しました。一部のラベルは再起動後に完全に適用されます。",
        "score_calc_error": "スコア計算エラー: {}",
        "tab_not_selected": "タブが選択されていません",
        "tab_info_error": "タブ情報取得エラー",
        "main_stat_missing": "{}: メインステータスが未入力です",
        "individual_score_title": "【{}】個別スコア計算 - {}\n",
        "echo_info": "【音骸情報】\n",
        "level": "レベル: {}\n",
        "effective_substat_count": "有効サブステ数: {}/5\n\n",
        "substat_header": "【サブステータス】\n",
        "none": "  （なし）\n",
        "score_by_method": "【評価方式別スコア】\n\n",
        "score_label": "   スコア: {:.2f} 点\n",
        "rating_label": "   評価: {}\n",
        "desc_label": "   説明: {}\n\n",
        "total_evaluation": "【総合評価】\n",
        "total_score": "総合スコア: {:.2f} 点\n",
        "total_rating": "総合評価: {}\n",
        "recommendation": "推奨度: {}\n",
        "batch_score_title": "【{}】音骸セット総合評価\n",
        "calculated_count": "計算済み音骸数: {}/{}\n",
        "echo_n_header": "\n【音骸 {}】{}\n",
        "set_total_score": "【セット全体の合計スコア】\n",
        "set_avg_score": "【セット全体の平均スコア】\n",
        "final_evaluation": "【最終評価】\n",
        "sss_desc": "SSS級 - 完璧な音骸セット！理論値級の性能です",
        "ss_desc": "SS級 - 非常に優秀なセット。ほぼ完成形です",
        "s_desc": "S級 - 優秀なセット。実戦で十分な性能です",
        "a_desc": "A級 - 良好なセット。使用に問題ありません",
        "b_desc": "B級 - 及第点。改善の余地があります",
        "c_desc": "C級 - 要改善。厳選を継続することをお勧めします",
        "normalized_score_desc": "各サブステを最大値で正規化し重み付け",
        "ratio_score_desc": "サブステ比率とダメージ上昇を考慮",
        "roll_quality_desc": "各サブステの引き強度を個別評価",
        "effective_stat_desc": "有効なサブステ数にボーナス付与",
        "normalized_score_label": "正規化スコア方式 (GameWith式)",
        "ratio_score_label": "比率重視方式 (Keisan式)",
        "roll_quality_label": "ロール品質方式",
        "effective_stat_label": "有効ステータス数方式",
        "cost_label": "コスト: {}",
        "score_point": "{:.2f}点",
        "score_per_item": "{:.2f}点/個",
        "score_point_count": "{:.2f}点 [{}個]",
        "total_score_label": "総合スコア",
        "total_label": "総合",
        "normalized_label": "正規化",
        "ratio_label": "比率",
        "roll_label": "ロール",
        "effective_label": "有効ステ",
        "effective_count_label": "有効数",
        "recommend_label": "推奨",
        "warning": "警告",
        "no_data": "計算可能な音骸データがありません",
        "individual_eval_done": "個別詳細評価完了: {} - 総合{:.2f}点",
        "batch_eval_done": "まとめて詳細評価完了: {}個計算",
        "calc_error": "計算エラー:\n{}",
        "batch_calc_error": "まとめて評価エラー: {}",
        "batch_error_msg": "まとめて計算でエラーが発生しました:\n{}",
        "image_load_error": "画像の読み込みに失敗しました:\n{}",
        "image_load_error_log": "画像読み込みエラー: {}",
        "pytesseract_not_installed": "pytesseractがインストールされていないためOCRを実行できません",
        "tesseract_found_path": "TesseractがPATHから発見されました: {}",
        "tesseract_not_found_sys": "Tesseractが見つかりません。パスを設定するか、システムにインストールしてください。",
        "ocr_error_title": "OCRエラー",
        "ocr_lang_data_error_log": "OCR言語データエラー: {}",
        "tesseract_exec_not_found": "Tesseract実行ファイルが見つかりません:\n{}",
        "tesseract_exec_error_log": "Tesseract実行ファイルエラー: {}",
        "ocr_process_error_log": "OCR処理エラー: {}",
        "crop_title": "画像切り取り",
        "crop_instruction": "マウスドラッグで切り取り範囲を指定してください。",
        "ok": "決定",
        "cancel": "キャンセル",
        "reset": "リセット",
        "crop_too_small": "選択範囲が小さすぎます",
        "text_color": "テキスト色:",
        "select_color": "色選択",
        "apply": "適用",
        "background_image": "背景画像:",
        "select_image": "画像を選択",
        "clear_image": "クリア",
        "bg_opacity": "背景不透明度:",
        "help_customization": "見た目のカスタマイズ ヘルプ",
        "font_settings": "フォント設定",
        "font_family": "フォント:",
        "default_font": "システムデフォルト",
        # Stats
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "攻撃力",
        "攻撃力%": "攻撃力%",
        "防御力": "防御力",
        "防御力%": "防御力%",
        "クリティカル率": "クリティカル率",
        "クリティカルダメージ": "クリティカルダメージ",
        "共鳴効率": "共鳴効率",
        "通常攻撃ダメージアップ": "通常攻撃ダメージアップ",
        "重撃ダメージアップ": "重撃ダメージアップ",
        "共鳴スキルダメージアップ": "共鳴スキルダメージアップ",
        "共鳴解放ダメージアップ": "共鳴解放ダメージアップ",
        "焦熱ダメージアップ": "焦熱ダメージアップ",
        "凝縮ダメージアップ": "凝縮ダメージアップ",
        "電導ダメージアップ": "電導ダメージアップ",
        "気動ダメージアップ": "気動ダメージアップ",
        "回折ダメージアップ": "回折ダメージアップ",
        "消滅ダメージアップ": "消滅ダメージアップ",
        "HP回復効果アップ": "HP回復効果アップ",
        # Ratings
        "rating_sss_norm": "SS級 - 最高品質",
        "rating_ss_norm": "S級 - 優秀",
        "rating_s_norm": "A級 - 実用的",
        "rating_b_norm": "B級 - 要改善",
        "rating_perf_ratio": "完璧 - 理論値に近い",
        "rating_exc_ratio": "優秀 - 十分強い",
        "rating_good_ratio": "良好 - 使用可能",
        "rating_avg_ratio": "普通 - 改善推奨",
        "rating_weak_ratio": "弱い - 厳選必要",
        "rating_god_roll": "神引き - 最高ロール連続",
        "rating_win_roll": "当たり - 高品質ロール多数",
        "rating_avg_roll": "平均的 - 標準的ロール",
        "rating_bad_roll": "ハズレ - 低品質ロール",
        "rating_perf_eff": "完璧 - 5有効ステ ({:.1f}点)",
        "rating_exc_eff": "優秀 - 4有効ステ ({:.1f}点)",
        "rating_good_eff": "良好 - 3有効ステ ({:.1f}点)",
        "rating_bad_eff": "要改善 - {}有効ステ ({:.1f}点)",
        "rating_sss_global": "SSS - 完璧な音骸セット!",
        "rating_ss_global": "SS - 非常に優秀",
        "rating_s_global": "S - 優秀",
        "rating_a_global": "A - 良好",
        "rating_b_global": "B - 合格",
        "rating_c_global": "C - 要改善",
        "rec_continue": "厳選継続",
        "rec_use": "使用推奨",
        "theme": "ライト/ダーク",
        "display_settings": "表示設定",
        # Character Names
        "CarlottaNew": "カルロッタNew",
        "Cantarella": "カンタレラ",
        "Tsubaki": "ツバキ",
        "Changli": "長離",
        "General": "汎用",
        "rating_sss_single": "SSS - 完璧な音骸! 理想的な性能です",
        "rating_ss_single": "SS - 非常に優秀な音骸",
        "rating_s_single": "S - 優秀な音骸",
        "rating_a_single": "A - 良好な音骸",
        "rating_b_single": "B - 使用可能",
        "rating_c_single": "C - 厳選推奨",
        # CV Method Ratings
        "rating_outstanding_cv": "最高級 - 70点以上 (SSS級)",
        "rating_excellent_cv": "非常に優秀 - 50~70点 (S級)",
        "rating_good_cv": "優秀 - 38~50点 (目標達成)",
        "rating_acceptable_cv": "合格 - 30~38点 (最低ライン)",
        "rating_weak_cv": "要厳選 - 30点未満",
        # Method Labels
        "cv_score_label": "CV換算方式 (コミュニティ標準)",
        "cv_score_desc": "会心値を基準とした評価（30点合格/38点目標）",
        # Method Selection
        "calc_methods": "計算方式:",
        "method_normalized": "正規化",
        "method_ratio": "比率重視",
        "method_roll": "ロール品質",
        "method_effective": "有効ステ数",
        "method_cv": "CV換算",
        "no_methods_selected": "少なくとも1つの計算方式を選択してください",
        "dark_theme": "ダーク",
        "light_theme": "ライト",
        "clear_theme": "クリア",
        "input_bg_color": "入力欄背景色",
        "reset": "リセット",
        "full_reset": "全設定リセット",
        "confirm_full_reset": "すべての表示設定をリセットしてもよろしいですか？",
        "help_customization": "カスタマイズガイド",
        "font_settings": "フォント設定",
        "font_family": "フォントファミリー:",
        "default_font": "システムデフォルト",
    },
    "en": {
        "app_title": "Wuthering Waves Echo Score Calculator",
        "char_setting_title": "Character Settings",
        "char_name": "Character Name:",
        "char_name_en": "English Name:",
        "char_name_en_placeholder": "Enter English name (e.g., Calcharo)",
        "cost_config": "Cost Config:",
        "echo_5_slot_config": "Echo 5-Slot Configuration",
        "cost_echo": "Cost {} Echo",
        "effective_substats_weights": "Effective Substats & Weights (5 slots)",
        "effective_substat_n": "Effective Substat {}",
        "weight": "Weight:",
        "save": "Save",
        "close": "Close",
        "error": "Error",
        "enter_char_name": "Please enter a character name",
        "enter_char_name_en": "Please enter an English name",
        "echo_main_stat_unselected": "Echo {} Main Stat not selected",
        "save_complete": "Save Complete",
        "save_msg": "Settings for {} saved",
        "basic_settings": "Basic Settings",
        "character": "Char:",
        "input_mode": "Input:",
        "manual": "Manual",
        "ocr": "OCR",
        "auto_main": "Auto Main",
        "calc_mode": "Calc:",
        "batch": "Batch",
        "single_only": "Single",
        "calculate": "Calculate",
        "export_txt": "Export TXT",
        "clear_all": "Clear All",
        "clear_tab": "Clear Tab",
        "char_setting": "Char Set",
        "help": "Help",
        "ocr_image": "OCR Image",
        "load_image": "Load Image",
        "paste_clipboard": "Paste Clipboard (Ctrl+V)",
        "perform_crop": "Crop",
        "crop_mode": "Crop Mode:",
        "drag": "Drag",
        "percent": "Percent",
        "top_percent": "Top%:",
        "right_percent": "Right%:",
        "no_image": "No Image",
        "calc_result": "Results",
        "log": "Log",
        "main_stat": "Main",
        "substats": "Substats",
        "ratio": "Ratio: {}",
        "tab_clear_success": "Cleared tab '{}'",
        "export_success": "Export Success",
        "export_msg": "Result exported to TXT file.",
        "ocr_library_missing": "OCR mode requires the following libraries:\n{}\n\nReverting to Manual mode.",
        "ocr_auto_fill_fail_no_tab": "OCR Auto-fill Failed: No tab selected",
        "ocr_auto_fill_fail_tab_not_found": "OCR Auto-fill Failed: Tab '{}' not found",
        "ocr_auto_fill_success": "OCR Auto-fill: Sub{} -> {} {}{}",
        "clipboard_no_image": "No image in clipboard",
        "clipboard_error": "Clipboard load error: {}",
        "image_not_loaded": "Image not loaded",
        "file_not_found": "File not found:\n{}",
        "image_select_cancelled": "Image selection cancelled",
        "select_image_file": "Select Image File",
        "image_files": "Image Files",
        "all_files": "All Files",
        "pillow_required": "Pillow is required for OCR mode.",
        "crop_cancel": "Crop cancelled",
        "image_loaded": "Image loaded: {}",
        "ocr_success": "OCR Success (Chars: {})",
        "ocr_no_text": "OCR Result: No text detected",
        "ocr_tesseract_not_found": "Tesseract executable not found (Config: {})",
        "ocr_lang_data_error": "OCR language data (jpn) not found.\nPlease install Tesseract Japanese data (jpn.traineddata).\nDetail: {}",
        "ocr_process_error": "OCR Process Error:\n{}",
        "data_save_success": "Data saved",
        "data_load_success": "Data loaded (Applied necessary items)",
        "data_load_error": "Load Failed: {}",
        "settings_loaded": "Settings loaded",
        "language": "Language:",
        "restart_required": "Restart Required",
        "restart_msg": "Language setting changed. Please restart the application to apply.",
        "language_changed_title": "Language Changed",
        "language_changed_message": "Language setting changed. Some labels will be fully applied after restart.",
        "score_calc_error": "Score Calc Error: {}",
        "tab_not_selected": "Tab not selected",
        "tab_info_error": "Tab info error",
        "main_stat_missing": "{}: Main stat missing",
        "individual_score_title": "[{}] Individual Score - {}\n",
        "echo_info": "[Echo Info]\n",
        "level": "Level: {}\n",
        "effective_substat_count": "Effective Substats: {}/5\n\n",
        "substat_header": "[Substats]\n",
        "none": "  (None)\n",
        "score_by_method": "[Score by Method]\n\n",
        "score_label": "   Score: {:.2f}\n",
        "rating_label": "   Rating: {}\n",
        "desc_label": "   Desc: {}\n\n",
        "total_evaluation": "[Total Evaluation]\n",
        "total_score": "Total Score: {:.2f}\n",
        "total_rating": "Total Rating: {}\n",
        "recommendation": "Recommendation: {}\n",
        "batch_score_title": "[{}] Echo Set Total Evaluation\n",
        "calculated_count": "Calculated Echoes: {}/{}\n",
        "echo_n_header": "\n[Echo {}] {}\n",
        "set_total_score": "[Set Total Score]\n",
        "set_avg_score": "[Set Average Score]\n",
        "final_evaluation": "[Final Evaluation]\n",
        "sss_desc": "SSS - Perfect set! Theoretical maximum performance.",
        "ss_desc": "SS - Excellent set. Almost complete.",
        "s_desc": "S - Great set. Sufficient for combat.",
        "a_desc": "A - Good set. No issues using it.",
        "b_desc": "B - Acceptable. Room for improvement.",
        "c_desc": "C - Needs improvement. Keep farming.",
        "normalized_score_desc": "Normalized by max value and weighted",
        "ratio_score_desc": "Considers substat ratio and damage increase",
        "roll_quality_desc": "Evaluates roll quality of each substat",
        "effective_stat_desc": "Bonus for number of effective substats",
        "normalized_score_label": "Normalized Score",
        "ratio_score_label": "Ratio Score",
        "roll_quality_label": "Roll Quality",
        "effective_stat_label": "Effective Stat Count",
        "cost_label": "Cost: {}",
        "score_point": "{:.2f} pts",
        "score_per_item": "{:.2f} pts/item",
        "score_point_count": "{:.2f} pts [{} items]",
        "total_score_label": "Total Score",
        "total_label": "Total",
        "normalized_label": "Norm",
        "ratio_label": "Ratio",
        "roll_label": "Roll",
        "effective_label": "Eff",
        "effective_count_label": "Eff#",
        "recommend_label": "Rec",
        "warning": "Warning",
        "no_data": "No calculable echo data",
        "individual_eval_done": "Individual eval done: {} - Total {:.2f} pts",
        "batch_eval_done": "Batch eval done: {} items calculated",
        "calc_error": "Calc Error:\n{}",
        "batch_calc_error": "Batch calc error: {}",
        "batch_error_msg": "Error in batch calculation:\n{}",
        "image_load_error": "Failed to load image:\n{}",
        "image_load_error_log": "Image load error: {}",
        "pytesseract_not_installed": "pytesseract not installed, cannot perform OCR",
        "tesseract_found_path": "Tesseract found in PATH: {}",
        "tesseract_not_found_sys": "Tesseract not found. Please configure path or install on system.",
        "ocr_error_title": "OCR Error",
        "ocr_lang_data_error_log": "OCR lang data error: {}",
        "tesseract_exec_not_found": "Tesseract executable not found:\n{}",
        "tesseract_exec_error_log": "Tesseract exec error: {}",
        "ocr_process_error_log": "OCR process error: {}",
        "crop_title": "Crop Image",
        "crop_instruction": "Drag mouse to select crop area.",
        "ok": "OK",
        "cancel": "Cancel",
        "reset": "Reset",
        "text_color": "Text Color:",
        "select_color": "Select Color",
        "apply": "Apply",
        "background_image": "Background Image:",
        "select_image": "Select Image",
        "clear_image": "Clear",
        "bg_opacity": "Background Opacity:",
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "ATK",
        "攻撃力%": "ATK%",
        "防御力": "DEF",
        "防御力%": "DEF%",
        "クリティカル率": "Crit Rate",
        "クリティカルダメージ": "Crit DMG",
        "共鳴効率": "Energy Regen",
        "通常攻撃ダメージアップ": "Basic ATK DMG Bonus",
        "重撃ダメージアップ": "Heavy ATK DMG Bonus",
        "共鳴スキルダメージアップ": "Skill DMG Bonus",
        "共鳴解放ダメージアップ": "Liberation DMG Bonus",
        "焦熱ダメージアップ": "Fusion DMG Bonus",
        "凝縮ダメージアップ": "Glacio DMG Bonus",
        "電導ダメージアップ": "Electro DMG Bonus",
        "気動ダメージアップ": "Aero DMG Bonus",
        "回折ダメージアップ": "Spectro DMG Bonus",
        "消滅ダメージアップ": "Havoc DMG Bonus",
        "HP回復効果アップ": "Healing Bonus",
        "rating_sss_norm": "SS - Top Quality",
        "rating_ss_norm": "S - Excellent",
        "rating_s_norm": "A - Practical",
        "rating_b_norm": "B - Needs Improvement",
        "rating_perf_ratio": "Perfect - Near Theoretical Max",
        "rating_exc_ratio": "Excellent - Very Strong",
        "rating_good_ratio": "Good - Usable",
        "rating_avg_ratio": "Average - Recommended to Improve",
        "rating_weak_ratio": "Weak - Needs Farming",
        "rating_god_roll": "God Roll - Max Rolls Streak",
        "rating_win_roll": "Win - Many High Rolls",
        "rating_avg_roll": "Average - Standard Rolls",
        "rating_bad_roll": "Loss - Low Quality Rolls",
        "rating_perf_eff": "Perfect - 5 Effective Stats ({:.1f} pts)",
        "rating_exc_eff": "Excellent - 4 Effective Stats ({:.1f} pts)",
        "rating_good_eff": "Good - 3 Effective Stats ({:.1f} pts)",
        "rating_bad_eff": "Improve - {} Effective Stats ({:.1f} pts)",
        "rating_sss_global": "SSS - Perfect Echo Set!",
        "rating_ss_global": "SS - Very Excellent",
        "rating_s_global": "S - Excellent",
        "rating_a_global": "A - Good",
        "rating_b_global": "B - Passing Grade",
        "rating_c_global": "C - Needs Improvement",
        "rec_continue": "Continue Farming",
        "rec_use": "Recommended to Use",
        "theme": "light/dark",
        "display_settings": "Display Settings",
        "rating_sss_single": "SSS - Perfect Echo!",
        "rating_ss_single": "SS - High Quality Echo",
        "rating_s_single": "S - Good Echo",
        "rating_a_single": "A - Decent Echo",
        "rating_b_single": "B - Usable",
        "rating_c_single": "C - Needs Improvement",
        "rating_outstanding_cv": "Outstanding - 70+ pts (SSS tier)",
        "rating_excellent_cv": "Excellent - 50~70 pts (S tier)",
        "rating_good_cv": "Good - 38~50 pts (Target Achieved)",
        "rating_acceptable_cv": "Acceptable - 30~38 pts (Passing Grade)",
        "rating_weak_cv": "Weak - Below 30 pts",
        "cv_score_label": "CV (Crit Value) Method - Community Standard",
        "cv_score_desc": "Crit-value based evaluation (30pt pass / 38pt target)",
        "calc_methods": "Calculation Methods:",
        "method_normalized": "Normalized",
        "method_ratio": "Ratio-Based",
        "method_roll": "Roll Quality",
        "method_effective": "Effective Stats",
        "method_cv": "CV (Crit Value)",
        "no_methods_selected": "Please select at least one calculation method",
        "dark_theme": "Dark",
        "light_theme": "Light",
        "clear_theme": "Clear",
        "input_bg_color": "Input Background Color",
        "reset": "Reset",
        "full_reset": "Reset All Display Settings",
        "confirm_full_reset": "Are you sure you want to reset all display settings?",
        "help_customization": "Customization Guide",
        "font_settings": "Font Settings",
        "font_family": "Font Family:",
        "default_font": "System Default",
        # Characters
        "CarlottaNew": "Carlotta New",
        "Cantarella": "Cantarella",
        "Tsubaki": "Tsubaki",
        "Changli": "Changli",
        "General": "General",
    },
    "zh-TW": {
        "app_title": "鳴潮 音骸評分計算器",
        "char_setting_title": "角色設定",
        "char_name": "角色名稱:",
        "char_name_en": "英文名稱:",
        "char_name_en_placeholder": "輸入英文名稱 (例如: Calcharo)",
        "cost_config": "Cost 構成:",
        "echo_5_slot_config": "音骸 5 欄位配置",
        "cost_echo": "Cost {} 音骸",
        "effective_substats_weights": "有效副詞條與權重係數 (5個)",
        "effective_substat_n": "有效副詞條 {}",
        "weight": "權重:",
        "save": "儲存",
        "close": "關閉",
        "error": "錯誤",
        "enter_char_name": "請輸入角色名稱",
        "enter_char_name_en": "請輸入英文名稱",
        "echo_main_stat_unselected": "音骸 {} 主詞條未選擇",
        "save_complete": "儲存完成",
        "save_msg": "已儲存 {} 的設定",
        "basic_settings": "基本設定",
        "character": "角色:",
        "input_mode": "輸入:",
        "manual": "手動",
        "ocr": "OCR",
        "auto_main": "自動主詞條",
        "calc_mode": "計算:",
        "batch": "批量",
        "single_only": "單個",
        "calculate": "計算",
        "export_txt": "導出 TXT",
        "clear_all": "全部清除",
        "clear_tab": "清除分頁",
        "char_setting": "角色設定",
        "help": "幫助",
        "ocr_image": "OCR 圖片",
        "load_image": "讀取圖片",
        "paste_clipboard": "從剪貼簿貼上 (Ctrl+V)",
        "perform_crop": "執行裁剪",
        "crop_mode": "裁剪模式:",
        "drag": "拖曳",
        "percent": "百分比",
        "top_percent": "上%:",
        "right_percent": "右%:",
        "no_image": "無圖片",
        "calc_result": "計算結果",
        "log": "日誌",
        "main_stat": "主詞條",
        "substats": "副詞條",
        "ratio": "倍率: {}",
        "tab_clear_success": "已清除分頁 '{}'",
        "export_success": "導出成功",
        "export_msg": "結果已導出至 TXT 檔案。",
        "ocr_library_missing": "OCR 模式需要以下庫:\n{}\n\n正在切換回手動模式。",
        "ocr_auto_fill_fail_no_tab": "OCR 自動填充失敗: 未選擇分頁",
        "ocr_auto_fill_fail_tab_not_found": "OCR 自動填充失敗: 找不到分頁 '{}'",
        "ocr_auto_fill_success": "OCR 自動填充: 副詞條 {} -> {} {}{}",
        "clipboard_no_image": "剪貼簿中無圖片",
        "clipboard_error": "剪貼簿讀取錯誤: {}",
        "image_not_loaded": "未讀取圖片",
        "file_not_found": "找不到檔案:\n{}",
        "image_select_cancelled": "取消圖片選擇",
        "select_image_file": "選擇圖片檔案",
        "image_files": "圖片檔案",
        "all_files": "所有檔案",
        "pillow_required": "OCR 模式需要 Pillow。",
        "crop_cancel": "取消裁剪",
        "image_loaded": "已讀取圖片: {}",
        "ocr_success": "OCR 成功 (字數: {})",
        "ocr_no_text": "OCR 結果: 未檢測到文字",
        "ocr_tesseract_not_found": "找不到 Tesseract 執行檔 (設定: {})",
        "ocr_lang_data_error": "找不到 OCR 語言數據 (jpn)。\n請安裝 Tesseract 日語數據 (jpn.traineddata)。\n詳情: {}",
        "ocr_process_error": "OCR 處理發生錯誤:\n{}",
        "data_save_success": "數據已儲存",
        "data_load_success": "數據讀取完成",
        "data_load_error": "讀取失敗: {}",
        "settings_loaded": "設定已讀取",
        "language": "語言:",
        "restart_required": "需要重啟",
        "restart_msg": "語言設定已更改。請重啟應用程式以生效。",
        "language_changed_title": "語言已更改",
        "language_changed_message": "語言設定已更改。部分標籤將在重啟後完全生效。",
        "score_calc_error": "評分計算錯誤: {}",
        "tab_not_selected": "未選擇分頁",
        "tab_info_error": "分頁信息錯誤",
        "main_stat_missing": "{}: 主詞條未輸入",
        "individual_score_title": "【{}】個別評分計算 - {}\n",
        "echo_info": "【音骸信息】\n",
        "level": "等級: {}\n",
        "effective_substat_count": "有效副詞條數: {}/5\n\n",
        "substat_header": "【副詞條】\n",
        "none": "  (無)\n",
        "score_by_method": "【評分方式】\n\n",
        "score_label": "   評分: {:.2f} 分\n",
        "rating_label": "   評價: {}\n",
        "desc_label": "   說明: {}\n\n",
        "total_evaluation": "【綜合評價】\n",
        "total_score": "綜合評分: {:.2f} 分\n",
        "total_rating": "綜合評價: {}\n",
        "recommendation": "推薦度: {}\n",
        "batch_score_title": "【{}】音骸套裝綜合評價\n",
        "calculated_count": "已計算音骸數: {}/{}\n",
        "echo_n_header": "\n【音骸 {}】{}\n",
        "set_total_score": "【套裝總分】\n",
        "set_avg_score": "【套裝平均分】\n",
        "final_evaluation": "【最終評價】\n",
        "sss_desc": "SSS級 - 完美的音骸套裝！性能接近理論值。",
        "ss_desc": "SS級 - 非常優秀的套裝。幾乎完成。",
        "s_desc": "S級 - 優秀的套裝。實戰性能充足。",
        "a_desc": "A級 - 良好的套裝。可以正常使用。",
        "b_desc": "B級 - 及格。還有提升空間。",
        "c_desc": "C級 - 待改進。建議繼續刷取。",
        "normalized_score_desc": "根據最大值正規化並加權",
        "ratio_score_desc": "考慮詞條比率與傷害提升",
        "roll_quality_desc": "評估每個副詞條的強化強度",
        "effective_stat_desc": "根據有效副詞條數量給予加成",
        "normalized_score_label": "正規化評分方式 (GameWith式)",
        "ratio_score_label": "比率重視方式 (Keisan式)",
        "roll_quality_label": "強化品質方式",
        "effective_stat_label": "有效詞條數方式",
        "cost_label": "Cost: {}",
        "score_point": "{:.2f} 分",
        "score_per_item": "{:.2f} 分/個",
        "score_point_count": "{:.2f} 分 [{}個]",
        "total_score_label": "綜合評分",
        "total_label": "綜合",
        "normalized_label": "正規化",
        "ratio_label": "比率",
        "roll_label": "品質",
        "effective_label": "有效詞條",
        "effective_count_label": "有效數",
        "recommend_label": "推薦",
        "warning": "警告",
        "no_data": "無可計算的音骸數據",
        "individual_eval_done": "個別評分完成: {} - 綜合 {:.2f} 分",
        "batch_eval_done": "批量評分完成: 已計算 {} 個",
        "calc_error": "計算錯誤:\n{}",
        "batch_calc_error": "批量計算錯誤: {}",
        "batch_error_msg": "批量計算發生錯誤:\n{}",
        "image_load_error": "圖片讀取失敗:\n{}",
        "image_load_error_log": "圖片讀取錯誤: {}",
        "pytesseract_not_installed": "未安裝 pytesseract，無法執行 OCR",
        "tesseract_found_path": "在 PATH 中找到 Tesseract: {}",
        "tesseract_not_found_sys": "找不到 Tesseract。請設定路徑或安裝至系統。",
        "ocr_error_title": "OCR 錯誤",
        "ocr_lang_data_error_log": "OCR 語言數據錯誤: {}",
        "tesseract_exec_not_found": "找不到 Tesseract 執行檔:\n{}",
        "tesseract_exec_error_log": "Tesseract 執行檔錯誤: {}",
        "ocr_process_error_log": "OCR 處理錯誤: {}",
        "crop_title": "圖片裁剪",
        "crop_instruction": "請拖曳鼠標指定裁剪範圍。",
        "ok": "確定",
        "cancel": "取消",
        "reset": "重置",
        "text_color": "文字顏色:",
        "select_color": "選擇顏色",
        "apply": "應用",
        "background_image": "背景圖片:",
        "select_image": "選擇圖片",
        "clear_image": "清除",
        "bg_opacity": "背景不透明度:",
        "HP": "生命值",
        "HP%": "生命值%",
        "攻撃力": "攻擊力",
        "攻撃力%": "攻擊力%",
        "防御力": "防禦力",
        "防御力%": "防禦力%",
        "クリティカル率": "暴擊率",
        "クリティカルダメージ": "暴擊傷害",
        "共鳴効率": "共鳴效率",
        "通常攻撃ダメージアップ": "普攻傷害加成",
        "重撃ダメージアップ": "重擊傷害加成",
        "共鳴スキルダメージアップ": "共鳴技能傷害加成",
        "共鳴解放ダメージアップ": "共鳴解放傷害加成",
        "焦熱ダメージアップ": "焦熱傷害加成",
        "凝縮ダメージアップ": "凝縮傷害加成",
        "電導ダメージアップ": "電導傷害加成",
        "気動ダメージアップ": "氣動傷害加成",
        "回折ダメージアップ": "回折傷害加成",
        "消滅ダメージアップ": "消滅傷害加成",
        "HP回復効果アップ": "治療效果加成",
        "rating_sss_norm": "SS - 最高品質",
        "rating_ss_norm": "S - 優秀",
        "rating_s_norm": "A - 實用",
        "rating_b_norm": "B - 待改進",
        "rating_perf_ratio": "完美 - 接近理論值",
        "rating_exc_ratio": "優秀 - 非常強大",
        "rating_good_ratio": "良好 - 可使用",
        "rating_avg_ratio": "普通 - 建議改進",
        "rating_weak_ratio": "弱 - 需要繼續刷取",
        "rating_god_roll": "神抽 - 連續最高強化品質",
        "rating_win_roll": "大獎 - 多個高品質強化",
        "rating_avg_roll": "平均 - 標準強化品質",
        "rating_bad_roll": "沒中 - 低品質強化",
        "rating_perf_eff": "完美 - 5 有效詞條 ({:.1f} 分)",
        "rating_exc_eff": "優秀 - 4 有效詞條 ({:.1f} 分)",
        "rating_good_eff": "良好 - 3 有效詞條 ({:.1f} 分)",
        "rating_bad_eff": "待改進 - {} 有效詞條 ({:.1f} 分)",
        "rating_sss_global": "SSS - 完美的音骸套裝！",
        "rating_ss_global": "SS - 非常優秀",
        "rating_s_global": "S - 優秀",
        "rating_a_global": "A - 良好",
        "rating_b_global": "B - 及格",
        "rating_c_global": "C - 待改進",
        "rec_continue": "繼續刷取",
        "rec_use": "建議使用",
        "theme": "亮色/深色",
        "display_settings": "顯示設定",
        "rating_sss_single": "SSS - 完美的音骸！",
        "rating_ss_single": "SS - 高品質音骸",
        "rating_s_single": "S - 優秀音骸",
        "rating_a_single": "A - 良好音骸",
        "rating_b_single": "B - 可使用",
        "rating_c_single": "C - 待改進",
        "rating_outstanding_cv": "頂級 - 70分以上 (SSS級)",
        "rating_excellent_cv": "非常優秀 - 50~70分 (S級)",
        "rating_good_cv": "優秀 - 38~50分 (達成目標)",
        "rating_acceptable_cv": "及格 - 30~38分 (最低限度)",
        "rating_weak_cv": "需刷取 - 30分以下",
        "cv_score_label": "CV (雙暴) 換算方式 (社群標準)",
        "cv_score_desc": "以雙暴值為基準的評估 (30分及格 / 38分目標)",
        "calc_methods": "計算方式:",
        "method_normalized": "正規化",
        "method_ratio": "比率重視",
        "method_roll": "強化品質",
        "method_effective": "有效詞條數",
        "method_cv": "CV 換算",
        "no_methods_selected": "請至少選擇一種計算方式",
        "dark_theme": "深色",
        "light_theme": "亮色",
        "clear_theme": "透明",
        "input_bg_color": "輸入框背景顏色",
        "reset": "重置",
        "full_reset": "重置所有顯示設定",
        "confirm_full_reset": "確定要重置所有顯示設定嗎？",
        "help_customization": "自定義指南",
        "font_settings": "字型設定",
        "font_family": "字型系列:",
        "default_font": "系統預設",
        # Characters
        "CarlottaNew": "卡洛塔New",
        "Cantarella": "坎塔蕾拉",
        "Tsubaki": "樁",
        "Changli": "長離",
        "General": "通用",
    },
}
